
version: 2

models:
  - name: int_customers
    schema: int_cust_n_affl
    description: "A Staging table for the customers data seeded from IDL and delta load"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: First Name
        description: "First Name of the Customer"
        tests:
          - not_null
      - name: Last Name
        description: "Last Name of the Customer"
        tests:
          - not_null

sources:
  - name: int_cust_n_affl
    database: postgres
    schema: int_cust_n_affl  
    tables:
      - name: int_customers